---
-   name: deploy
    hosts: 'Modulbank.BuhTemplate'
    become: yes
    tasks:
      - name: upload binaries
        synchronize:
          src: '../out/'
          dest: '/usr/local/bin/modulbank/Modulbank.BuhTemplate/'
          delete: yes

      - name: upload systemd unit
        synchronize:
          src: 'Modulbank.BuhTemplate.service'
          dest: '/etc/systemd/system/Modulbank.BuhTemplate.service'

      - name: upload conf file
        synchronize:
          src: '../etc/Modulbank.BuhTemplate.conf'
          dest: '/etc/modulbank/Modulbank.BuhTemplate.conf'

      - name: restart service
        systemd:
          name: 'Modulbank.BuhTemplate'
          state: restarted
          daemon_reload: yes