concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "Modul Dotnet Debian Runner"
  url = "http://gitlab.server.host/"
  token = "<gitlab.server.token>"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "dotnet-debian-build"
    pull_policy = "if-not-present"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache",
    "/var/lib/nuget/packages/:/root/.nuget/packages",
    "/var/lib/deb:/var/lib/deb",
    "/var/run/docker.sock:/var/run/docker.sock"]
    shm_size = 0
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]